src/java/model/Card.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author LENOVO
 */
public class Card {
    private int id;
    private String term;
    private String definition;
    private int studySetId;

    public Card() {
    }

    public Card(int id, String term, String definition, int studySetId) {
        this.id = id;
        this.term = term;
        this.definition = definition;
        this.studySetId = studySetId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTerm() {
        return term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public int getStudySetId() {
        return studySetId;
    }

    public void setStudySetId(int studySetId) {
        this.studySetId = studySetId;
    }
}

src/java/model/Class.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author asus
 */
public class Class {
    private int id;
    private String name;
    private String desc;
    private boolean isInvite;
    private String inviteCode;
    private boolean isEdit;
    private String schoolName;
    private int userId;

    public Class() {
    }

    public Class(int id, String name, String desc, boolean isInvite, String inviteCode, boolean isEdit, String schoolName, int userId) {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.isInvite = isInvite;
        this.inviteCode = inviteCode;
        this.isEdit = isEdit;
        this.schoolName = schoolName;
        this.userId = userId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public boolean isIsInvite() {
        return isInvite;
    }

    public void setIsInvite(boolean isInvite) {
        this.isInvite = isInvite;
    }

    public String getInviteCode() {
        return inviteCode;
    }

    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    public boolean isIsEdit() {
        return isEdit;
    }

    public void setIsEdit(boolean isEdit) {
        this.isEdit = isEdit;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    
}

src/java/model/Exercises.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author MSII
 */
public class Exercises {
    private int ExID;
    private String ExName;
    private String Answers;
    private int PageID;

    public Exercises() {
    }

    public Exercises(int ExID, String ExName, String Answers, int PageID) {
        this.ExID = ExID;
        this.ExName = ExName;
        this.Answers = Answers;
        this.PageID = PageID;
    }

    public int getExID() {
        return ExID;
    }

    public void setExID(int ExID) {
        this.ExID = ExID;
    }

    public String getExName() {
        return ExName;
    }

    public void setExName(String ExName) {
        this.ExName = ExName;
    }

    public String getAnswers() {
        return Answers;
    }

    public void setAnswers(String Answers) {
        this.Answers = Answers;
    }

    public int getPageID() {
        return PageID;
    }

    public void setPageID(int PageID) {
        this.PageID = PageID;
    }
    
}

src/java/model/Folder.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.DAO;
import java.util.ArrayList;

/**
 *
 * @author LENOVO
 */
public class Folder {
    private int id;
    private String title;
    private String desc;
    private int userId;
    private boolean isShare;

    public Folder() {
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public boolean isIsShare() {
        return isShare;
    }

    public void setIsShare(boolean isShare) {
        this.isShare = isShare;
    }
    
    public Folder(int id, String title, String desc, int userId, boolean isShare) {
        this.id = id;
        this.title = title;
        this.desc = desc;
        this.userId = userId;
        this.isShare = isShare;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }
    
    public int getNumberStudySet() {
        DAO d = new DAO();
        ArrayList<Integer> listS = d.getStudySetIdByFolderId(id);
        return listS.size();
    }
}

src/java/model/StudySet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import dal.DAO;
import java.util.ArrayList;

/**
 *
 * @author LENOVO
 */
public class StudySet {

    private int id;
    private String title;
    private String description;
    private boolean isShare;
    private int userId;

    public StudySet() {
    }

    public StudySet(int id, String title, String description, boolean isShare, int userId) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.isShare = isShare;
        this.userId = userId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isIsShare() {
        return isShare;
    }

    public void setIsShare(boolean isShare) {
        this.isShare = isShare;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getNumberCard() {
        DAO d = new DAO();
        ArrayList<Card> listC = d.getAllCardInSet(id);
        return listC.size();
    }

    public String getAuthor() {
        DAO d = new DAO();
        User user = d.getUserByUserId(userId);
        String name = user.getName();
        return name;
    }
}

web/card.jsp
<%-- 
    Document   : card
    Created on : Dec 9, 2022, 5:00:33 AM
    Author     : LENOVO
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link rel="stylesheet" href="css/card.css"/>
    </head>
    <body>
        <label>
            <input type="checkbox" />
                <div class="flip-card">
                    <div class="front">FONT CARD</div>
                    <div class="back">BACK CARD</div>
                </div>
        </label>
    </body>
</html>

web/changePass.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Reset password | Quizlet</title>
        <link rel="stylesheet" href="css/change.css"/>
    </head>

    <body>
        <%@include file="header.jsp" %>
        <c:if test="${checkVerifyLink}">
            <div class="change-body">
                <h2 class="text-center">Reset password</h2>  
                <form action="change" method = "post" class="change-form mt-4">
                    <p style="color: red">${requestScope.error}</p>
                    <p style="color: red">${requestScope.invalidpass}</p>
                    <input type="password" class="form-change-pass" name ="pass" required/>
                    <p>MẬT KHẨU MỚI </p>
                    <input type="password" class="form-change-pass" name="repass" required/>
                    <p>XÁC NHẬN MẬT KHẨU MỚI</p>
                    <button type = "submit" class="btn-change-pass">LƯU MẬT KHẨU</button>
                </form>
            </div>
        </c:if>
            <div class="change-body">
                <h2 class="text-center">Reset password</h2>  
                <form action="change" method = "post" class="change-form mt-4">
                    <p style="color: red">${requestScope.error}</p>
                    <p style="color: red">${requestScope.invalidpass}</p>
                    <input type="password" class="form-change-pass" name ="pass" required/>
                    <p>MẬT KHẨU MỚI </p>
                    <input type="password" class="form-change-pass" name="repass" required/>
                    <p>XÁC NHẬN MẬT KHẨU MỚI</p>
                    <button type = "submit" class="btn-change-pass">LƯU MẬT KHẨU</button>
                </form>
            </div>

        <%@include file="footer.jsp" %>

    </body>

</html>

web/checkMail.jsp
<%-- 
    Document   : checkMail
    Created on : Mar 6, 2023, 7:20:45 PM
    Author     : asus
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Check your email! | Quizlet</title>
        <link rel="stylesheet" href="css/check.css"/>
    </head>
    <body>
        <%@include file="header.jsp" %>
        <div class="container-check">
            <h1>Check your email! | Quizlet</h1>
            <p>We've sent an email to ${mail}</p>
            <p>Please check your spam folder if you don't see the email in your inbox.</p>
            <a href="url">Need more help?</a>
        </div>
        <%@include file="footer.jsp" %>
    </body>
</html>

web/createSet.jsp
<%-- 
    Document   : createSet
    Created on : Dec 12, 2022, 3:47:47 AM
    Author     : LENOVO
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="java.util.*" %>
<%@page import="model.Card" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Tạo học phần mới | Quizlet</title>
        <link rel="stylesheet" href="css/createSet.css"/>
    </head>
    <body>
        <%@include file="header.jsp" %>
        <% ArrayList<Card> listC = (ArrayList<Card>)request.getSession().getAttribute("listC"); %>
        <div class="container-create">
            <form action="createSet" method="post">
                <div class="header-create">
                    <div class="create">Tạo học phần mới</div>
                    <input class="btn-create" value="Tạo" type="submit">
                </div>
                <input type="text" required name="titleSet" value="${requestScope.titleSet}" placeholder="Nhập tiêu đề, ví dụ: 'Sinh học - Chương 22: Tiến hóa'"  class="input-set"/><br/>
                <div class="title-input">TIÊU ĐỀ</div>
                <input type="text" name="descSet" value="${requestScope.descSet}" placeholder="Thêm mô tả..." class="input-set"/><br/>
                <div class="title-input">MÔ TẢ</div>
                <div class="container-share">
                    <input class="share-btn" id="isShare" name="isShare" type="checkbox" ${isShare ? "checked" : ""} value="${isShare}"/>
                    <label for="isShare" class="share-text">Chia sẻ với mọi người</label>
                </div>
                <div class="error-add" style="${err_card != null ? "" : "display: none"}">${requestScope.err_card}</div>
                <c:forEach var="i" begin="1" end="${requestScope.numberCard}" >
                    <div class="container-card">
                        <div class="card-header">
                            <div class="title-input">${i}</div>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <input type="text" name="card-title" class="input-card" value="${listC.get(i-1).getTerm()}"/><br/>
                                <div class="title-input">THUẬT NGỮ</div>
                            </div>
                            <div class="card-desc">
                                <input type="text" name="card-desc" class="input-card" value="${listC.get(i-1).getDefinition()}"/><br/>
                                <div class="title-input">ĐỊNH NGHĨA</div>
                            </div>
                        </div>
                    </div>
                </c:forEach>
                <div class="container-add">
                    <div class="number-card">${requestScope.numberCard+1}</div>
                    <input type="submit" name="btn-increase" class="title-add" value="+ THÊM THẺ"/>
                    <div></div>
                </div>
                <input type="submit" value="Tạo" class="add-footer"/>
            </form>
        </div>
    </body>
</html>

web/explanations.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page import="dal.*" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Lời giải chuyên gia</title>
        <script src="https://kit.fontawesome.com/1c2c2462bf.js" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="css/explanations.css"/>
    </head>
    <body>
        <%@include file="header.jsp" %>


        <div class="Book-title row">
            <h2>Duyệt sách</h2>

            <div class="col-12 col-md-2 col-sm-4">
                <br>
                <img src="${b.getImage()}" alt="${b.getTitle()}" />
            </div>
            <div class="col-12 col-md-10 col-sm-8" >
                <h3>${b.getTitle()}</h3>
                <p>${b.getEdition()}</p>
                <p>ISBN: ${b.getIsbn()}</p>
                <p>${b.getAuthors()}</p>
            </div>


        </div>
        <div class="answer">
            <h5><strong>Lời giải sách giáo khoa</strong></h5>

            <c:forEach items="${listC}" var="c" varStatus="loop">

                <div class="accordion" id="accordionPanelsStayOpenExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="panelsStayOpen-headingOne" >
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne" style="background-color: #2e3856">
                                ${c.getChapterName()}
                            </button>

                        </h2>

                        <div class="row">


                            <div id="panelsStayOpen-collapseOne" class="col-12 col-md-6 accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                                <c:set var="listP" value="${d.getAllPageByChapterID(c.getChapterID())}" />
                                <div class="accordion-body accordion-body-left">
                                    <c:forEach items="${listP}" var="p">
                                        <c:set var="listE" value="${d.getAllExByPageID(p.getPageID())}" />
                                        <p onclick="handleSelectPage(${p.getPageID()}, ${listE.size()})">${p.getPageName()}</p>
                                    </c:forEach>
                                </div>

                            </div>

                            <div id="panelsStayOpen-collapseOne" class="col-12 col-md-6 accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">

                                <div class="accordion-body accordion-body-right">
                                    <c:forEach items="${listP}" var="p">
                                        <c:set var="listE" value="${d.getAllExByPageID(p.getPageID())}" />
                                        
                                             <c:forEach items="${listE}" var="e">
                                            <a href="answer?id=${e.getExID()}&isbn=${b.getIsbn()}&pId=${p.getPageID()}&cid=${p.getChapterID()}" class="ex${p.getPageID()} exercises" >${e.getExName()}</a>
                                            
                                        </c:forEach>
                                        
                                    </c:forEach>
                                </div>

                            </div>

                        </div>

                    </div>
                </div>

            </c:forEach>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script>
            var listEx = document.getElementsByClassName("exercises");
            
            function handleSelectPage(pId, numChap) {
                let className = "ex" +  pId;
                let listE = document.getElementsByClassName(className);
                console.log(listE);
                for(var j=0; j<listEx.length; j++) {
                    listEx[j].style.display = "none";
                }
                for(var i=0; i<listE.length; i++) { 
                    listE[i].style.display = "block";
                }
            }
        </script>
    </body>
</html>

web/forget.jsp
<%-- 
    Document   : verify
    Created on : Dec 8, 2022, 3:14:19 PM
    Author     : LENOVO
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Forgotten Password |Quizlet</title>
        <link rel="stylesheet" href="css/forget.css"/>
    </head>
    <body>
        <%@include file="header.jsp" %>
        <div class="container-reset">
            <div class="container-form">
                <div class="wrapper-form">
                    <h2 class="verify-title">Reset your password</h2>
                    <p>Enter your Quizlet username or the email address you signed up with. We'll email you a link to log in and reset your password.</p>
                    <form action="forget" method="post">
                        <input type="text" name="email" placeholder="Username or email address" class="input-form"/>
                        <div class="text-form">Username or email address</div> 
                        <input type="submit" value="Submit" class="submit-button"/>
                    </form>
                </div>
                <p style="color: red">${requestScope.error}</p>
            </div>
        </div>
        <%@include file="footer.jsp" %>
    </body>
</html>

web/slider.jsp
<%-- 
   Document   : slider.jsp
   Created on : Dec 13, 2022, 1:32:11 AM
   Author     : LENOVO
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link rel="stylesheet" href="css/slider.css" />
    </head>
    <body>
        <div class="container-slide">
            <div class="slide">
                <label>
                    <input type="checkbox" />
                    <div class="flip-card">
                        <div class="front">FONT CARD1</div>
                        <div class="back">BACK CARD1</div>
                    </div>
                </label>
            </div>
            <div class="slide">
                <label>
                    <input type="checkbox" />
                    <div class="flip-card">
                        <div class="front">FONT CARD2</div>
                        <div class="back">BACK CARD2</div>
                    </div>
                </label>
            </div>  
            <div class="slide">
                <label>
                    <input type="checkbox" />
                    <div class="flip-card">
                        <div class="front">FONT CARD3</div>
                        <div class="back">BACK CARD3</div>
                    </div>
                </label>
            </div>
        </div>
        <div class="card-footer">
            <div class="btn-prev" onclick="goPrev()" >Prev</div>
            <div class="btn-next" onclick="goNext()" >Next</div>
        </div>
    </body>
    <script>
        const slides = document.querySelectorAll(".slide");
        var count = 0;
        slides.forEach((slide, index) => {
            var pos = index * 100;
            slide.style.left = pos + "%";
        });
        const slideImage = () => {
            slides.forEach(slide => {
                var counter = count * 100;
                slide.style.transform = "translateX(-" + counter + "%)";
            })
        }
        const goNext = () => {
            count++;
            slideImage();
        }

        const goPrev = () => {
            count--;
            slideImage();
        }

    </script>
</html>

web/update.jsp
<%-- 
    Document   : update
    Created on : Dec 13, 2022, 11:33:27 AM
    Author     : LENOVO
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="java.util.*" %>
<%@page import="model.Card" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Sửa học phần | Quizlet</title>
        <link rel="stylesheet" href="css/update.css" />
    </head>
    <body>
        <%@include file="header.jsp" %>
        <div class="container-create">
            <form action="update" method="post">
                <div class="header-create">
                    <div class="create"><a href="flashCards?id=${requestScope.id}"><i class="fa-solid fa-chevron-left"></i> Trở về học phần</a></div>
                    <input class="btn-create" value="Hoàn tất" type="submit">
                </div>
                <input type="text" required name="titleSet" value="${requestScope.titleSet}" placeholder="Nhập tiêu đề, ví dụ: 'Sinh học - Chương 22: Tiến hóa'"  class="input-set"/><br/>
                <div class="title-input">TIÊU ĐỀ</div>
                <input type="text" name="descSet" value="${requestScope.descSet}" placeholder="Thêm mô tả..." class="input-set"/><br/>
                <div class="title-input">MÔ TẢ</div>
                <div class="container-share">
                    <input class="share-btn" id="isShare" name="isShare" type="checkbox" ${requestScope.isShare ? "checked" : ""} value="${isShare}"/>
                    <label for="isShare" class="share-text">Chia sẻ với mọi người</label>
                </div>
                <c:forEach var="i" begin="1" end="${requestScope.numCard}" >
                    <div class="container-card">
                        <div class="card-header">
                            <div class="title-input">${i}</div>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <input type="text" name="card-title" class="input-card" value="${listC.get(i-1).getTerm()}"/><br/>
                                <div class="title-input">THUẬT NGỮ</div>
                            </div>
                            <div class="card-desc">
                                <input type="text" name="card-desc" class="input-card" value="${listC.get(i-1).getDefinition()}"/><br/>
                                <div class="title-input">ĐỊNH NGHĨA</div>
                            </div>
                        </div>
                        <input type="text" name="id-card" value="${listC.get(i-1).getId()}" hidden />
                    </div>
                </c:forEach>
                <div class="container-add">
                    <div class="number-card">${requestScope.numCard+1}</div>
                    <input type="submit" name="btn-increase" class="title-add" value="+ THÊM THẺ"/>
                    <div></div>
                </div>
                <input type="submit" value="Hoàn tất" class="add-footer"/>
            </form>
        </div>
    </body>
</html>